import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const outputRoot = join(projectRoot, 'lib')

const clientModules = [
  ['runtime.cjs', 'src/client/runtime.cjs'],
  ['style-lifecycle.cjs', 'src/client/style-lifecycle.cjs'],
  ['theme-lifecycle.cjs', 'src/client/theme-lifecycle.cjs'],
  ['compat/rc5-adapter.cjs', 'src/client/compat/rc5-adapter.cjs'],
]

async function readProjectFile(relativePath) {
  return readFile(join(projectRoot, relativePath), 'utf8')
}

function svgDataUri(svg) {
  return `data:image/svg+xml,${encodeURIComponent(svg)
    .replaceAll('%20', ' ')
    .replaceAll('%3D', '=')}`
}

function wrapModule(id, source) {
  return `${JSON.stringify(id)}: function (module, exports, require) {\n${source}\n}`
}

await rm(outputRoot, { force: true, recursive: true })
await mkdir(outputRoot, { recursive: true })

const [hostSource, styleSource, tokenSource, motionSource, whaleSource] = await Promise.all([
  readProjectFile('src/index.js'),
  readProjectFile('src/styles/yinkesi.css'),
  readProjectFile('src/theme/tokens.json'),
  readProjectFile('src/theme/motion.json'),
  readProjectFile('src/assets/deepseek-whale.svg'),
])

const tokenData = JSON.parse(tokenSource)
const motionData = JSON.parse(motionSource)
const whaleDataUri = svgDataUri(whaleSource.trim())
const styleText = styleSource
  .replaceAll('__YINKESI_WHALE_DATA_URI__', whaleDataUri)
  .replaceAll('__YINKESI_WHALE_MASK__', whaleDataUri)
  .replaceAll('__YINKESI_MOTION_PRESS__', motionData.duration.press)
  .replaceAll('__YINKESI_MOTION_HOVER__', motionData.duration.hover)
  .replaceAll('__YINKESI_MOTION_PANEL__', motionData.duration.panel)
  .replaceAll('__YINKESI_MOTION_REDUCED__', motionData.duration.reduced)
  .replaceAll('__YINKESI_EASING_SPRING__', motionData.easing.spring)
  .replaceAll('__YINKESI_EASING_STANDARD__', motionData.easing.standard)
  .replaceAll('__YINKESI_SCALE_PRESS__', String(motionData.scale.press).replace(/^0\./, '.'))

if (/__YINKESI_[A-Z0-9_]+__/.test(styleText)) {
  throw new Error('Yinkesi CSS contains an unresolved build placeholder')
}

const moduleSources = await Promise.all(
  clientModules.map(async ([id, relativePath]) => [id, await readProjectFile(relativePath)]),
)

const clientSource = `/* Generated by scripts/build.mjs. Do not edit. */
window.__ModuleLoader__.load({
  id: "dsh-yinkesi",
  factory: (require) => {
    "use strict";
    const __externalRequire = require;
    const __factories = {
      ${moduleSources.map(([id, source]) => wrapModule(id, source)).join(',\n      ')}
    };
    const __cache = Object.create(null);
    const __resolve = (from, request) => {
      if (!request.startsWith('.')) return request;
      const parts = from.split('/');
      parts.pop();
      for (const part of request.split('/')) {
        if (!part || part === '.') continue;
        if (part === '..') parts.pop();
        else parts.push(part);
      }
      return parts.join('/');
    };
    const __load = (id) => {
      if (__cache[id]) return __cache[id].exports;
      const factory = __factories[id];
      if (!factory) return __externalRequire(id);
      const module = { exports: {} };
      __cache[id] = module;
      factory(module, module.exports, (request) => {
        const resolved = __resolve(id, request);
        return __factories[resolved] ? __load(resolved) : __externalRequire(request);
      });
      return module.exports;
    };
    const runtime = __load("runtime.cjs");
    return runtime.createYinkesiPlugin({
      styleText: ${JSON.stringify(styleText)},
      tokens: ${JSON.stringify(tokenData)},
      motion: ${JSON.stringify(motionData)},
      whaleDataUri: ${JSON.stringify(whaleDataUri)},
      packageVersion: "0.2.0"
    });
  }
});
`

await Promise.all([
  writeFile(join(outputRoot, 'index.js'), `${hostSource.trim()}\n`, 'utf8'),
  writeFile(join(outputRoot, 'client.js'), clientSource, 'utf8'),
])
